# Modify the TKC_NAME value as per the requirements
# Modify the configmap-volume configMap name to the appropriate value
apiVersion: batch/v1
kind: Job
metadata:
  name: app-tkc-creation
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: argocd-tkc-post
        image: whoami6443/argocd-hook:0.1.3
        command: 
          - "/script.sh"
        imagePullPolicy: IfNotPresent
        env:
        - name: TKC_NAME
          value: "workload-vsphere-tkg1"
        volumeMounts:
        - name: configmap-volume
          mountPath: /template
      volumes:
      - name: configmap-volume
        configMap:
          name: argocd-app-configmap
      restartPolicy: Never
      serviceAccountName: demo1-argocd-argocd-application-controller
     # serviceAccountName: argocd-hook
  backoffLimit: 2
