apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: ${ARGOCD_ENV_CLUSTER_NAME}
  namespace: demo1
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["192.168.32.0/20"]
    pods:
      cidrBlocks: ["192.168.0.0/20"]
    serviceDomain: "cluster.local"
  topology:
    class: tanzukubernetescluster
    version: ${ARGOCD_ENV_TKR}
    controlPlane:
      replicas: 1
      metadata:
        annotations:
          run.tanzu.vmware.com/resolve-os-image: os-name=ubuntu
    workers:
      machineDeployments:
        - class: node-pool
          name: node-pool-1
          replicas: 1
          metadata:
            annotations:
              run.tanzu.vmware.com/resolve-os-image: os-name=ubuntu          
    variables:
      - name: ntp
        value: time.google.com
      - name: vmClass
        value: best-effort-medium
      - name: storageClass
        value: ${ARGOCD_ENV_STORAGE_CLASS}
      - name: defaultStorageClass
        value: ${ARGOCD_ENV_STORAGE_CLASS}
      - name: clusterEncryptionConfigYaml
        value: |
          apiVersion: apiserver.config.k8s.io/v1
          kind: EncryptionConfiguration
          resources:
            - resources:
                - secrets
              providers:
                - aescbc:
                    keys:
                      - name: key1
                        secret: QiMgJGYXudtljldVyl+AnXQQlk7r9iUXBfVKqdEfKm8=
                - identity: {}
# ADDITIONAL VALUES
      - name: nodePoolVolumes
        value:
        - capacity:
            storage: "15Gi"
          mountPath: "/var/lib/containerd"
          name: containerd
          storageClass: ${ARGOCD_ENV_STORAGE_CLASS}
        - capacity:
            storage: "15Gi"
          mountPath: "/var/lib/kubelet"
          name: kubelet
          storageClass: ${ARGOCD_ENV_STORAGE_CLASS}
      - name: controlPlaneVolumes
        value:
        - capacity:
            storage: "15Gi"
          mountPath: "/var/lib/containerd"
          name: containerd
          storageClass: ${ARGOCD_ENV_STORAGE_CLASS}
        - capacity:
            storage: "15Gi"
          mountPath: "/var/lib/kubelet"
          name: kubelet
          storageClass: ${ARGOCD_ENV_STORAGE_CLASS}
